<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="8" total="16" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="78" started-at="2016-02-16T21:41:23Z" finished-at="2016-02-16T21:41:23Z">
    <groups>
      <group name="Positive">
        <method signature="HashMapDemoTest.HashmapgetvaluefromKey()[pri:0, instance:com.test.HashMapDemoTest@28d47c65]" name="HashmapgetvaluefromKey" class="com.test.HashMapDemoTest"/>
        <method signature="LargestNumberTest.findLargestNumber()[pri:0, instance:com.test.LargestNumberTest@1193b520]" name="findLargestNumber" class="com.test.LargestNumberTest"/>
        <method signature="NullpointerTest.ArrayIndexOutofBound()[pri:0, instance:com.test.NullpointerTest@37f92637]" name="ArrayIndexOutofBound" class="com.test.NullpointerTest"/>
        <method signature="PalindromeTest.findPalindrome()[pri:0, instance:com.test.PalindromeTest@785850e3]" name="findPalindrome" class="com.test.PalindromeTest"/>
        <method signature="WordReverseTest.Wordreversetest()[pri:0, instance:com.test.WordReverseTest@6e26a4ce]" name="Wordreversetest" class="com.test.WordReverseTest"/>
      </group> <!-- Positive -->
      <group name="negative">
        <method signature="InheritanceTest.Methodoverloadingneg()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverloadingneg" class="com.test.InheritanceTest"/>
        <method signature="InheritanceTest.Methodoverridingneg()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverridingneg" class="com.test.InheritanceTest"/>
        <method signature="WordReplaceTest.wordReplaceneg()[pri:0, instance:com.test.WordReplaceTest@2b0e08e1]" name="wordReplaceneg" class="com.test.WordReplaceTest"/>
      </group> <!-- negative -->
      <group name="positive">
        <method signature="InheritanceTest.Methodoverloadingpos()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverloadingpos" class="com.test.InheritanceTest"/>
        <method signature="InheritanceTest.Methodoverridingpos()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverridingpos" class="com.test.InheritanceTest"/>
        <method signature="WordReplaceTest.wordReplacepos()[pri:0, instance:com.test.WordReplaceTest@2b0e08e1]" name="wordReplacepos" class="com.test.WordReplaceTest"/>
      </group> <!-- positive -->
      <group name="Negative">
        <method signature="HashMapDemoTest.Hashmapgetvaluefromkeneg()[pri:0, instance:com.test.HashMapDemoTest@28d47c65]" name="Hashmapgetvaluefromkeneg" class="com.test.HashMapDemoTest"/>
        <method signature="LargestNumberTest.findLargestNumberneg()[pri:0, instance:com.test.LargestNumberTest@1193b520]" name="findLargestNumberneg" class="com.test.LargestNumberTest"/>
        <method signature="PalindromeTest.findPalindromeneg()[pri:0, instance:com.test.PalindromeTest@785850e3]" name="findPalindromeneg" class="com.test.PalindromeTest"/>
        <method signature="WordReverseTest.Wordreversetestneg()[pri:0, instance:com.test.WordReverseTest@6e26a4ce]" name="Wordreversetestneg" class="com.test.WordReverseTest"/>
      </group> <!-- Negative -->
    </groups>
    <test name="Test" duration-ms="78" started-at="2016-02-16T21:41:23Z" finished-at="2016-02-16T21:41:23Z">
      <class name="com.test.WordReplaceTest">
        <test-method status="FAIL" signature="wordReplaceneg()[pri:0, instance:com.test.WordReplaceTest@2b0e08e1]" name="wordReplaceneg" duration-ms="4" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<true> but was:<false>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<true> but was:<false>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:192)
	at com.test.WordReplaceTest.wordReplaceneg(WordReplaceTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wordReplaceneg -->
        <test-method status="PASS" signature="wordReplacepos()[pri:0, instance:com.test.WordReplaceTest@2b0e08e1]" name="wordReplacepos" duration-ms="2" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- wordReplacepos -->
      </class> <!-- com.test.WordReplaceTest -->
      <class name="com.test.PalindromeTest">
        <test-method status="PASS" signature="findPalindrome()[pri:0, instance:com.test.PalindromeTest@785850e3]" name="findPalindrome" duration-ms="2" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findPalindrome -->
        <test-method status="FAIL" signature="findPalindromeneg()[pri:0, instance:com.test.PalindromeTest@785850e3]" name="findPalindromeneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<false> but was:<true>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<false> but was:<true>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:185)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:192)
	at com.test.PalindromeTest.findPalindromeneg(PalindromeTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findPalindromeneg -->
      </class> <!-- com.test.PalindromeTest -->
      <class name="com.test.LargestNumberTest">
        <test-method status="PASS" signature="findLargestNumber()[pri:0, instance:com.test.LargestNumberTest@1193b520]" name="findLargestNumber" duration-ms="2" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findLargestNumber -->
        <test-method status="FAIL" signature="findLargestNumberneg()[pri:0, instance:com.test.LargestNumberTest@1193b520]" name="findLargestNumberneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<98> but was:<63>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<98> but was:<63>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at com.test.LargestNumberTest.findLargestNumberneg(LargestNumberTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- findLargestNumberneg -->
      </class> <!-- com.test.LargestNumberTest -->
      <class name="com.test.HashMapDemoTest">
        <test-method status="PASS" signature="HashmapgetvaluefromKey()[pri:0, instance:com.test.HashMapDemoTest@28d47c65]" name="HashmapgetvaluefromKey" duration-ms="12" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- HashmapgetvaluefromKey -->
        <test-method status="FAIL" signature="Hashmapgetvaluefromkeneg()[pri:0, instance:com.test.HashMapDemoTest@28d47c65]" name="Hashmapgetvaluefromkeneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<nishitha> but was:<smitha>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<nishitha> but was:<smitha>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.test.HashMapDemoTest.Hashmapgetvaluefromkeneg(HashMapDemoTest.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Hashmapgetvaluefromkeneg -->
      </class> <!-- com.test.HashMapDemoTest -->
      <class name="com.test.NullpointerTest">
        <test-method status="PASS" signature="ArrayIndexOutofBound()[pri:0, instance:com.test.NullpointerTest@37f92637]" name="ArrayIndexOutofBound" duration-ms="2" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ArrayIndexOutofBound -->
        <test-method status="FAIL" signature="Nullpointerpos()[pri:0, instance:com.test.NullpointerTest@37f92637]" name="Nullpointerpos" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="org.testng.TestException">
            <message>
              <![CDATA[
Method NullpointerTest.Nullpointerpos()[pri:0, instance:com.test.NullpointerTest@37f92637] should have thrown an exception of type class java.lang.ArithmeticException]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.TestException: 
Method NullpointerTest.Nullpointerpos()[pri:0, instance:com.test.NullpointerTest@37f92637] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1383)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:683)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.TestException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Nullpointerpos -->
      </class> <!-- com.test.NullpointerTest -->
      <class name="com.test.InheritanceTest">
        <test-method status="FAIL" signature="Methodoverloadingneg()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverloadingneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<13> but was:<12>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<13> but was:<12>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at com.test.InheritanceTest.Methodoverloadingneg(InheritanceTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Methodoverloadingneg -->
        <test-method status="PASS" signature="Methodoverloadingpos()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverloadingpos" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Methodoverloadingpos -->
        <test-method status="PASS" signature="Methodoverridingneg()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverridingneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Methodoverridingneg -->
        <test-method status="FAIL" signature="Methodoverridingpos()[pri:0, instance:com.test.InheritanceTest@266901dc]" name="Methodoverridingpos" duration-ms="0" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<35> but was:<12>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<35> but was:<12>
	at org.testng.AssertJUnit.fail(AssertJUnit.java:59)
	at org.testng.AssertJUnit.failNotEquals(AssertJUnit.java:364)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:80)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:245)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:252)
	at com.test.InheritanceTest.Methodoverridingpos(InheritanceTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Methodoverridingpos -->
      </class> <!-- com.test.InheritanceTest -->
      <class name="com.test.WordReverseTest">
        <test-method status="PASS" signature="Wordreversetest()[pri:0, instance:com.test.WordReverseTest@6e26a4ce]" name="Wordreversetest" duration-ms="2" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Wordreversetest -->
        <test-method status="FAIL" signature="Wordreversetestneg()[pri:0, instance:com.test.WordReverseTest@6e26a4ce]" name="Wordreversetestneg" duration-ms="1" started-at="2016-02-16T13:41:23Z" finished-at="2016-02-16T13:41:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:< This  is  the  string  which  is reveresed> but was:< This is the string which is reveresed>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:< This  is  the  string  which  is reveresed> but was:< This is the string which is reveresed>
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:101)
	at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:108)
	at com.test.WordReverseTest.Wordreversetestneg(WordReverseTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Wordreversetestneg -->
      </class> <!-- com.test.WordReverseTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
