<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SANISU2" name="com.test.NullpointerTest" tests="2" failures="0" timestamp="16 Feb 2016 21:41:24 GMT" time="0.003" errors="1">
  <testcase name="Nullpointerpos" time="0.001" classname="com.test.NullpointerTest">
    <error type="org.testng.TestException" message="
Method NullpointerTest.Nullpointerpos()[pri:0, instance:com.test.NullpointerTest@37f92637] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method NullpointerTest.Nullpointerpos()[pri:0, instance:com.test.NullpointerTest@37f92637] should have thrown an exception of type class java.lang.ArithmeticException
	at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:89)
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1383)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:683)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </error>
  </testcase> <!-- Nullpointerpos -->
  <testcase name="ArrayIndexOutofBound" time="0.002" classname="com.test.NullpointerTest"/>
</testsuite> <!-- com.test.NullpointerTest -->
